function createaxes(Y1)
%CREATEAXES(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-Jun-2018 22:09:03

% Create axes
axes1 = axes;
hold(axes1,'on');



% Create plot
plot(Y1);

box(axes1,'on');
